### PR TITLE
Support for Gnome 3.24

### PR DESCRIPTION
**Pull request by imrvelj**
Tested on Ubuntu 17.04. Haven't found any bugs.

Screenshot: [screen](https://i.imgur.com/3T3N2L9.png)

### CODE REVIEW

**Comment by jderose9** [comment]
Thanks very much for testing! Do you know if this is showing up on extensions.gnome.org currently in 3.24? I thought metadata changes to explicit indicate support for new versions was no longer going to be required so I didn't bother submitting a new version.

**Comment by imrvelj** [comment]
Glad to have helped. :smile:
I'll check it as soon as I can.

**Comment by imrvelj** [comment]
Wow, it's still greyed out and won't install... :astonished:

**Comment by franglais125** [comment]
@imrvelj It is still pending review... It can take 1 or 2 weeks for it to be live on e.g.o!
https://extensions.gnome.org/review/

**Comment by imrvelj** [comment]
Oh, didn't know that, thanks for the info.

**Pull request merged**
