### PR TITLE
Implement overlay numbers for the hotkeys

### PR DESCRIPTION
**Pull request by franglais125**
This is very similar to what was done in dash-to-dock with @micheleg's help.

Thoughts?

screenshot from 2017-02-11 19 13 56

### CODE REVIEW

**Comment by jderose9** [comment]
First of all.. this is awesome!!! Thanks so much.

I had some thoughts I wanted to talk out before merging.

1. I am currently storing the preview timeout options in integer milliseconds and I notice you are using decimal seconds. I think I'd like to keep the storage consistent at least. Does it make sense to the user to ask for one setting in ms and the other in seconds? I think it is ok if the typical value is an order of magnitude different, but I'm curious what you think. (I definitely want to make a decision on this before merging because altering the schema down the road will affect users when they upgrade).

2. If I have the overlay turned off, it doesn't display when I press the shortcut combo. But, I think my personal expectation would be to have the setting control only whether it shows up when I trigger an application (Super + Number), as I would probably disable the automated overlay display but still want to pull up the overlay explicitly with the shortcut sometimes. If I don't want the overlay to show up on explicit button press, I could clear out the shortcut combo. What do you think?

3. Does the timeout need to be tied to control both the automated display and explicit shortcut press? I'm finding hard to identify a value that doesn't feel too long for application launches or too short for explicit presses. Maybe the explicit presses can be a fixed (non-configurable) length?

4. I think my personal preferred implementation would be if I could hold the modifier key to see the overlay and then it would disappear when I launched an application. So for example, Hold Super > Overlay appears while Super is pressed > Press Number > Application launches & Overlay disappears. Did you look into this sort of flow at all? I'm not sure how reasonable it is to capture the modifier key presses alone in Gnome.

5. I found the text for the overlay shortcut a little confusing. It says "Shortcut for the options above". The plural threw me off a bit as I wasn't sure which options it was referring to. I think it might be better to be explicit "Shortcut to display the number overlay". Also the word "Syntax" was confusing to me. Are you ok with me updating a couple of these labels?

6. This may be a non-issue depending on changes from the above items but since we do this elsewhere I'd like to be consistent in having any settings disabled if another settings makes them irrelevant. For instance, disabling Shortcut textbox when the overlay is disabled.

7. I know we talked about this before, but it seems that since you allow the overlay combination to be pressed, you may be closer now to understanding how we can change the Super key to another key combination for launching the application?

Please don't take this long list the wrong way - I'm very excited to include this feature and really appreciate your effort! I also don't mind helping with changes but I didn't want to change your code around without discussing. Thanks again.

**Comment by franglais125** [comment]
Hi, thanks for considering this!

First of all, one of my computers is still on Debian Jessie (Gnome 3.14), so I can't test dash-to-panel all the time. My workflow so far goes better with dash-to-dock, but I see the value of your extension and trying to improve it seems worth it. So if at some point a PR for a feature feels clunky, feel free to criticize as perhaps there is something I'm missing.

1. I'll change the value to milliseconds, no problem!

2. Makes sense, I'll produce a patch and we'll see how it goes. Thanks!

3. This is really up to you! They don't need to be tied, again, I'll introduce your suggestion, and we can see if it "feels" right.

4. This is indeed how I had first implemented it (I liked it much more), but then quickly realized that this is not allowed in Wayland... The reason is you can't track keys (shortcuts being managed by the Shell itself, so it passes them on to whatever requests an action), to prevent key-logging. So, we can either leave it as it is, or have two code-paths for X/Wayland sessions. This is IMO not really the way to go, and the reason why I ended up using a configurable shortcut, but up to you.

5. Yes, I overlooked this when porting from dash-to-dock. If you look at how we did it for dash-to-dock, you'll see that there is another sub-option "show dock" (hence, the plural). To be honest, I'd like to include this for dash-to-panel as well, but there is (AFAIK) no internal display handling, e.g. autohide. If the dock/panel is hidden, we can make it appear for a moment, so that one can see what shortcut to trigger. I'll leave this as a to-do, I don't know how interested you are in something like this?

6. Sure thing, fair remark!

7. I'm not sure I understand the question. You mean using `<Ctrl>`+some letter? As I said above, you need to create a "shortcut", i.e. modifiers are not enough. Not sure if this answers your question.

Looking forward to improving it! I don't think I'll be able to send new commits before Wednesday. However, feel free to modify as you see fit :). Let me know if anything else comes up.

Cheers,
Fran

**Comment by jderose9** [comment]
> First of all, one of my computers is still on Debian Jessie (Gnome 3.14), so I can't test dash-to-panel all the time. My workflow so far goes better with dash-to-dock, but I see the value of your extension and trying to improve it seems worth it. 

Well thanks so much for your effort.. especially if you aren't even using it!

> This is really up to you! They don't need to be tied, again, I'll introduce your suggestion, and we can see if it "feels" right.

I'm not really sure. My first thought was that the overlay stayed up too long when launching an application, so I reduced the timeout to .5 seconds. But, I also didn't notice immediately that I could trigger the overlay manually with the shortcut. Once I saw that and used it, the overlay didn't stay up very long because I had reduced the timeout. I figured I didn't need it popping up automatically if I could manually trigger it, but when I disabled it, it stopped coming up even with the shortcut. I guess the only thing I feel strongly about is having some way to trigger it with the shortcut but not have it pop up automatically when launching applications. Other than that, maybe it's just best to get it out there and see if any feedback comes in.

> This is indeed how I had first implemented it (I liked it much more), but then quickly realized that this is not allowed in Wayland... The reason is you can't track keys (shortcuts being managed by the Shell itself, so it passes them on to whatever requests an action), to prevent key-logging. So, we can either leave it as it is, or have two code-paths for X/Wayland sessions. This is IMO not really the way to go, and the reason why I ended up using a configurable shortcut, but up to you.

Bummer. I don't think it's worthwhile to maintain two separate implementations, especially with most gnome distributions switching over to wayland.

> If the dock/panel is hidden, we can make it appear for a moment, so that one can see what shortcut to trigger. I'll leave this as a to-do, I don't know how interested you are in something like this?

I would like to add the autohide feature at some point. It's not a straight merge though of the dash-to-dock implementation due to the preview windows and widgets with popups where you actually navigate the mouse outside of the panel, yet the panel still has to remain open.

> I'm not sure I understand the question. You mean using <Ctrl>+some letter? As I said above, you need to create a "shortcut", i.e. modifiers are not enough. Not sure if this answers your question.

I'm personally accustomed to Super+Number to switch workspaces, so I thought that configuring some other modifier combo (Super+Ctrl+Number) or something along those lines would be great. Maybe there could be one input textbox for the modifier combination and that would write out all 10 of the individual settings values?

I was also trying to figure out if I gnome would let me bind the overlay shortcut to just <Super> (seems like no) or a use a specific left or right modifier key in the combination, such as <Super_L>q (seems like a no also).

Thanks again!

**Comment by franglais125** [comment]
Ok, so here we go. First iteration of improvements! As you can see there are 3 new commits. There is a caveat, explained at the end. I hope it's clear, as it's not so easy to explain.

- [5eee608ebc7728817388e0c4d48a9d084eaacc1f] I rebased onto your master, as you had some new commits. So this is just the original one actually, just rebased.
- [68452db035d2981e2fad1221171a64e9ae37ee33] Implements your suggestions 1, 2, 3, 5 and 6.
- [015e9c247f779f83472e509f1f513c1a98b8ab56] Implements your last suggestion: configurable prefix for hotkeys,

I think it is more consistent now with dash-to-panel. I reorganized a bit the settings and tried to followed your guidelines, I hope I got them right.
I **think** I implemented your suggestions 1, 2, 3, 5 and 6 as you requested, but let me know if I missed something (some were a bit intertwined). I skipped number 4 as that was the X/Wayland one.

As for 7 (the last commit), this is the tricky one. I actually don't think it is as useful as it sounded. Perhaps you can make it work with your key combos.
- Using `<Ctrl>` (and combinations) has the problem of launching a new instance every time.
- Using `<Shift>` (and combinations) will have the effect of using the advanced click options. E.g. `<Super><Shift>1` will be interpreted as "Click + Shift + 1".
- Using `<Alt>` alone breaks some apps, like Firefox and gnome-terminal tab-switching.
In the end we are left with `<Super><Alt>` as the only true alternative.

If you test the new version, is this your experience as well? This is why I kept the last part as a separate commit, so we can simply remove it if you find it's not really useful. However if you somehow make it work, perhaps we can improve it.

**Comment by jderose9** [comment]
Wow, you are organized!

Everything looks good to me. I agree something different should be done about the assignable shortcut due to the issues you mentioned. What do you think of a drop-down with only two options? "<Super>" and "<Super><Alt>" (Defaulted to "<Super>")? This way the user won't be searching around for a working combination. That's a lot of keys to press if you use Shift or Ctrl on top of <Super><Alt>, but the only other option I see is to just remove it and I'd really like to have an alternate mapping option.

Too bad I can't seem to find a way to map Super_L and Super_R individually in gnome.. Have you?

**Comment by franglais125** [comment]
Having a drop-down with two options sounds much more reasonable! I guess you forgot to fill the quotes ("") with `<Super>` and `<Super><Alt>`? With default being...`<Super>`?

As for Super_L and Super_R, I think we can't distinguish between them using Gdk, at least I didn't find any reference for a way of doing it. Only reference seems to be "Super" https://people.gnome.org/~gcampagna/docs/Gdk-3.0/Gdk.ModifierType.html

**Comment by jderose9** [comment]
>  I guess you forgot to fill the quotes ("") with <Super> and <Super><Alt>? With default being...<Super>?

Guess I forgot to escape the angle brackets, but you have it exactly right.

This looks good to me! Should I go ahead and merge?

**Comment by franglais125** [comment]
I think it's fine to merge as it is. At this point it would be useful to get some feedback from users, to see if there are more improvements needed!

**Pull request merged**
