### PR TITLE
windowPreview.js: two small fixes.

### PR DESCRIPTION
**Pull request by franglais125**
This tries to avoid errors (and hopefully crashes) when using window previews.
Particularly, it helps a bit when closing applications and/or when
locking/unlocking the screen the srceen.

_onDestroy():
1. disconnect the signal to `_queueResize()`
2. disconnect the `notify::title` signal

I don't know if it's enough to fix https://github.com/jderose9/dash-to-panel/issues/170, but I hope at least it can help a bit.

### CODE REVIEW

**Comment by franglais125** [comment]
Here is a sample of the errors each fix prevents:

1.
```
May 27 14:58:26 v131 gnome-shell[1400]: JS ERROR: Invalid work id 30: Error: Invalid work id 30
                                        queueDeferredWork@resource:///org/gnome/shell/ui/main.js:651
                                        thumbnailPreview<._queueResize@/home/franglais125/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/windowPreview.js:673
                                        wrapper@resource:///org/gnome/gjs/modules/lang.js:178
```

2.
```
May 27 14:58:22 v131 gnome-shell[1400]: clutter_text_get_text: assertion 'CLUTTER_IS_TEXT (self)' failed
May 27 14:58:22 v131 gnome-shell[1400]: clutter_text_set_text: assertion 'CLUTTER_IS_TEXT (self)' failed
```

**Comment by franglais125** [comment]
I just added [ecf41463ac1b6540d0f1971e16206a5e8deefb0e] to fix other errors. These warning on the logs had been haunting me for some time, and I could never find the exact origin. I just did away with them!

Sample error (for each iconContainer, notiuce the number "9", corresponding to the 9th item on the taskbar):
```
May 27 18:50:22 v131 gnome-shell[17718]: st_widget_get_theme_node called on the widget [0x555a56c93c30 Gjs_DashItemContainer.dash-item-container ("9")] which is not in the stage.
May 27 18:50:22 v131 gnome-shell[17718]: st_widget_get_theme_node called on the widget [0x555a546cd460 StButton.app-well-app running1:last-child first-child ("9")] which is not in the stage.
May 27 18:50:22 v131 gnome-shell[17718]: st_widget_get_theme_node called on the widget [0x555a5672a990 StWidget:last-child first-child ("9")] which is not in the stage.
```

**Comment by franglais125** [comment]
Just before you consider this, I'll look into it when I find more time. Feel free to investigate meanwhile of course! It's certainly not ready to be merged, as it's causing some crashes.

**Comment by jderose9** [comment]
@franglais125 Yes I saw your comments in the issue, I will leave open until they get worked out. Thank you!

**Comment by franglais125** [comment]
@jderose9 I'll close this for now, as I haven't made significant progress on this front. I'll reopen if I find an actual fix. This was more of a WIP. Cheers!

**Pull request closed without merging**
