### PR TITLE
Implement hotkeys for dash-to-panel.

### PR DESCRIPTION
**Pull request by franglais125**
`<Sup> + Num` to activate/launch apps

@jderose9 Thanks for taking a look!

### CODE REVIEW

**Comment by franglais125** [comment]
Forgot to mention: the default is already off in this PR.

**Comment by jderose9** [comment]
Awesome, thanks! I don't understand why the key bindings are in the settings schema if they aren't configurable? Is that the only way to apply custom keybindings?

**Comment by franglais125** [comment]
The reason is that this is the way it is suggested to do it. You can check the review of other extensions that have something similar [1], where it is suggested one should do it like this. The reference is an example I found, but I saw this in other places too.

Workspaces-to-dock has a setting to configure a keyboard shortcut, so it is definitely feasible. At the moment, I'm trying to implement this for dash-to-dock, for a number overlay [2]. Once I finish that, I can come back with that experience and add a configuration in the settings.

[1] https://extensions.gnome.org/review/4131
[2] example: https://www.youtube.com/watch?v=2Avkhxt69f4

**Comment by jderose9** [comment]
Sounds good. Thanks for helping out!

**Comment by franglais125** [comment]
Thanks for considering this feature :)

**Pull request merged**
