### PR TITLE
Add French translation

### PR DESCRIPTION
**Pull request by LaurentTreguier**
This PR adds French translations.
Other `.po` files are changed because I did a `make mergepo` before beginning to translate.

### CODE REVIEW

**Comment by franglais125** [comment]
Awesome!

When using this in a session in French, does the text for the application icon ("9 dots") get translated?
i.e. "Show Desktop" to "Afficher le bureau"?

**Comment by LaurentTreguier** [comment]
I'm not sure I understand which text you are referring to... Is the "9 dots" button the one for displaying applications ? If this is the case then it's working fine.
However I don't get any text when hovering over the "Show Desktop" button (which is what the "Show Desktop" string seems to be about). Even when not using the French translations actually...

**Comment by jderose9** [comment]
@LaurentTreguier I think he means the options in the right click menu.

**Comment by LaurentTreguier** [comment]
Oh ok... It doesn't seem to take the translations into account for those. Does it work with other translations ?

**Comment by jderose9** [comment]
Thank you!

**Comment by jderose9** [comment]
@LaurentTreguier I didn't understand the commit a8f48b33327d6b1fb303041bc9a48d49557b0d12, so I reverted it. It seemed that several languages were merged into each file. If it was a mistake, no problem, but if I am misunderstanding please let me know. Thanks again for the translation!

**Comment by LaurentTreguier** [comment]
@jderose9 I simply started with `make mergepo` before starting to translate, this is why every language file is modified by this commit I think

**Comment by jderose9** [comment]
@LaurentTreguier Ah I see, thanks! I noticed that there were new translations, but I guess those were added automatically. For instance in `cs_CZ.po` There is this:


#: Settings.ui.h:58
msgid "Show Activities Button"
msgstr "Zobrazit tlačítko aktivit"
  
#: Settings.ui.h:28
#, fuzzy
msgid "Show Desktop Button"
msgstr "Zobrazit tlačítko aktivit"


You can see they both have the same translation and the "Show Desktop Button" is new. I guess it tries to match automatically, thus the `fuzzy`. But, it seems to cause more harm than good so maybe I should turn it off..

**Comment by LaurentTreguier** [comment]
@jderose9 I don't think it causes much harm, `fuzzy` automatically prevents the translated string from being actually used. It's more of a simple suggestion for when the actual translating begins

**Comment by jderose9** [comment]
@LaurentTreguier ahhh I see. Sorry for the misujband thanks for explaining!

**Comment by franglais125** [comment]
@jderose9 sorry, I was away for a few days! What @LaurentTreguier explained is exactly right :)

The language tools are quite smart on their own, they:
- Remove obsolete strings (they appear as commented out at the bottom of the .po files)
- Avoid duplicated translations
- Introduce new strings with the `fuzzy` tag, so that they are not used until a translator manually removes that (and properly translates the string).

If you like, you can do this yourself (`make mergepo`), you commit the changes with a "updating po files" commit tag or something, and you can then ping the translators, say ~ a few days before a release. This will ensure a nice upgrade transition for users/contributors :)

Also, thanks for your attention to this!

**Pull request merged**
