### PR TITLE
Adding cs_CZ translation

### PR DESCRIPTION
**Pull request by zeten30**
Hi, 

I've created cs_CZ translation. Would you like to add it?

Cheers
Milan

### CODE REVIEW

**Comment by jderose9** [comment]
Nice, thank you!!

**Comment by zeten30** [comment]
YW 😄

**Comment by AsciiWolf** [comment]
I may be wrong, but I thought that Czech translations should be called `cs`, not `cs_CZ`.

**Comment by zeten30** [comment]
Check https://github.com/jderose9/dash-to-panel/pull/380

**Pull request merged**
